<?php
namespace Packfire\Net\Http;

/**
 * Test class for ClientBrowser.
 * Generated by PHPUnit on 2012-09-17 at 07:57:53.
 */
class ClientBrowserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Net\Http\ClientBrowser
     */
    public function testConstants()
    {
        $this->assertEquals('Chrome', ClientBrowser::CHROME);
        $this->assertEquals('Firefox', ClientBrowser::FIREFOX);
        $this->assertEquals('IE', ClientBrowser::IE);
        $this->assertEquals('Safari', ClientBrowser::SAFARI);
        $this->assertEquals('Opera', ClientBrowser::OPERA);
        $this->assertEquals('', ClientBrowser::UNKNOWN);
    }
}
