<?php
namespace Packfire\Net\Http;

/**
 * Test class for Method.
 * Generated by PHPUnit on 2012-02-15 at 17:59:13.
 */
class MethodTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers \Packfire\Net\Http\Method
     */
    public function testConstants()
    {
        $this->assertEquals('GET', Method::GET);
        $this->assertEquals('POST', Method::POST);
        $this->assertEquals('PUT', Method::PUT);
        $this->assertEquals('DELETE', Method::DELETE);
        $this->assertEquals('HEAD', Method::HEAD);
        $this->assertEquals('PATCH', Method::PATCH);
        $this->assertEquals('TRACE', Method::TRACE);
        $this->assertEquals('OPTIONS', Method::OPTIONS);
    }
}
