<?php

pload('packfire.net.http.pHttpClientBrowser');

/**
 * Test class for pHttpClientBrowser.
 * Generated by PHPUnit on 2012-09-17 at 07:57:53.
 */
class pHttpClientBrowserTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testConstants(){
        $this->assertEquals('Chrome', pHttpClientBrowser::CHROME);
        $this->assertEquals('Firefox', pHttpClientBrowser::FIREFOX);
        $this->assertEquals('IE', pHttpClientBrowser::IE);
        $this->assertEquals('Safari', pHttpClientBrowser::SAFARI);
        $this->assertEquals('Opera', pHttpClientBrowser::OPERA);
        $this->assertEquals('', pHttpClientBrowser::UNKNOWN);
    }

}