<?php

pload('packfire.net.http.pHttpMethod');

/**
 * Test class for pHttpMethod.
 * Generated by PHPUnit on 2012-02-15 at 17:59:13.
 */
class pHttpMethodTest extends PHPUnit_Framework_TestCase {
    
    function testConstants(){
        $this->assertEquals('GET', pHttpMethod::GET);
        $this->assertEquals('POST', pHttpMethod::POST);
        $this->assertEquals('PUT', pHttpMethod::PUT);
        $this->assertEquals('DELETE', pHttpMethod::DELETE);
        $this->assertEquals('HEAD', pHttpMethod::HEAD);
        $this->assertEquals('PATCH', pHttpMethod::PATCH);
        $this->assertEquals('TRACE', pHttpMethod::TRACE);
        $this->assertEquals('OPTIONS', pHttpMethod::OPTIONS);
    }

}