<?php
namespace Packfire\Database;

/**
 * Test class for Expression.
 * Generated by PHPUnit on 2012-09-03 at 07:13:15.
 */
class ExpressionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Database\Expression
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @covers \Packfire\Database\Expression::__construct
     */
    protected function setUp()
    {
        $this->object = new Expression('NOW()');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Database\Expression::expression
     */
    public function testExpression()
    {
        $this->assertEquals('NOW()', $this->object->expression());
    }

}
