<?php

pload('packfire.database.pDbExpression');

/**
 * Test class for pDbExpression.
 * Generated by PHPUnit on 2012-09-03 at 07:13:15.
 */
class pDbExpressionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pDbExpression
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pDbExpression('NOW()');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pDbExpression::expression
     */
    public function testExpression() {
        $this->assertEquals('NOW()', $this->object->expression());
    }

}