<?php

require_once dirname(__FILE__) . '/../../../../packfire/template/moustache/pMoustache.php';

/**
 * Test class for pMoustache.
 * Generated by PHPUnit on 2012-09-19 at 05:09:54.
 */
class pMoustacheTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pMoustache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pMoustache('Hello {{name}}{{#intro}}, my name is {{intro}}{{/intro}}!');
        $this->object->parameters(array('name' => 'world'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pMoustache::template
     */
    public function testTemplate() {
        $this->object->template('Good day {{name}}!');
        $this->assertEquals('Good day world!', $this->object->render());
    }

    /**
     * @covers pMoustache::parameters
     */
    public function testParameters() {
        $this->object->parameters(array('name' => 'Jack', 'intro' => 'Jill'));
        $this->assertEquals('Hello Jack, my name is Jill!', $this->object->render());
    }

    /**
     * @covers pMoustache::render
     */
    public function testRender() {
        $this->assertEquals('Hello world!', $this->object->render());
    }

}