<?php

pload('packfire.response.pJsonResponse');

/**
 * Test class for pJsonResponse.
 * Generated by PHPUnit on 2012-06-18 at 02:17:03.
 */
class pJsonResponseTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testResponse() {
        $data = array(
            'data' => 5
        );
        $object = new pJsonResponse($data);
        $this->assertEquals('application/json', $object->headers()->get('Content-Type'));
        $this->assertEquals(json_encode($data), $object->body());
        $this->assertEquals($object->body(), $object->output());
    }

    public function testResponse2() {
        $data = array(
            'data' => 5
        );
        $object = new pJsonResponse($data, 'test');
        $this->assertEquals('text/javascript', $object->headers()->get('Content-Type'));
        $this->assertEquals('test(' . json_encode($data) . ')', $object->body());
        $this->assertEquals($object->body(), $object->output());
    }

}