<?php

pload('packfire.response.pPhpSerializeResponse');

/**
 * Test class for pPhpSerializeResponse.
 * Generated by PHPUnit on 2012-09-19 at 04:39:02.
 */
class pPhpSerializeResponseTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testResponse(){
        $data = array(
            'data' => 5
        );
        $object = new pPhpSerializeResponse($data);
        $this->assertEquals('text/plain', $object->headers()->get('Content-Type'));
        $this->assertEquals(serialize($data), $object->body());
        $this->assertEquals($object->body(), $object->output());
    }

}