<?php

pload('packfire.response.pRedirectResponse');
pload('packfire.net.http.pHttpResponseCode');

/**
 * Test class for pRedirectResponse.
 * Generated by PHPUnit on 2012-06-18 at 02:13:45.
 */
class pRedirectResponseTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testResponse() {
        $url = 'http://example.com/';
        $object = new pRedirectResponse($url);
        $this->assertEquals(pHttpResponseCode::HTTP_302, $object->code());
        $this->assertEquals($url, $object->headers()->get('Location'));
        $this->assertEquals('', $object->body());
        $this->assertEquals('', $object->output());
    }

    public function testResponse2() {
        $url = 'http://example.com/';
        $object = new pRedirectResponse($url, pHttpResponseCode::HTTP_301);
        $this->assertEquals(pHttpResponseCode::HTTP_301, $object->code());
        $this->assertEquals($url, $object->headers()->get('Location'));
        $this->assertEquals('', $object->body());
        $this->assertEquals('', $object->output());
    }

}