<?php

pload('packfire.response.pResponse');

/**
 * Test class for pResponse.
 * Generated by PHPUnit on 2012-09-19 at 04:59:07.
 */
class pResponseTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pResponse::build
     */
    public function testBuild() {
        $data = array('data' => 5);
        $object = new pResponse('php');
        $response = $object->build($data);
        $this->assertInstanceOf('pPhpSerializeResponse', $response);
        $this->assertEquals(serialize($data), $response->output());
    }

    /**
     * @covers pResponse::create
     */
    public function testCreate() {
        $data = array('data' => 5);
        $response = pResponse::create($data, 'json');
        $this->assertInstanceOf('pJsonResponse', $response);
        $this->assertEquals(json_encode($data), $response->output());
    }

}