<?php

namespace Packfire\Response;

/**
 * Test class for YamlResponse.
 * Generated by PHPUnit on 2012-09-13 at 16:49:33.
 */
class YamlResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Response\YamlResponse
     */
    public function testResponse()
    {
        $data = array(
            'data' => 5
        );
        $object = new YamlResponse($data);
        $this->assertEquals('application/x-yaml', $object->headers()->get('Content-Type'));
        $this->assertEquals("\n---\ndata: 5\n...\n", $object->body());
        $this->assertEquals($object->body(), $object->output());
    }

    /**
     * @covers \Packfire\Response\YamlResponse
     */
    public function testResponse2()
    {
        $object = new YamlResponse("\n---\ndata: 5\n...\n");
        $this->assertEquals('application/x-yaml', $object->headers()->get('Content-Type'));
        $this->assertEquals("\n---\ndata: 5\n...\n", $object->body());
        $this->assertEquals($object->body(), $object->output());
    }
}
