<?php

pload('packfire.model.pObjectObserver');
require_once('mocks/tSampleModel.php');

/**
 * Test class for pObjectObserver.
 * Generated by PHPUnit on 2012-08-04 at 03:00:58.
 */
class pObjectObserverTest extends PHPUnit_Framework_TestCase {

    protected $model;
    
    /**
     * @var pObjectObserver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->model = new tSampleModel();
        $this->object = new pObjectObserver($this->model);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pModelWatcher::model
     */
    public function testModel() {
        $this->assertNotEmpty($this->object->model());
        $this->assertInstanceOf('tSampleModel', $this->object->model());
    }

    /**
     * @covers pModelWatcher::on
     */
    public function testOn() {
        $this->object->on('change', array($this, 'changeListener'));
        $this->changed = false;
        $this->object->title = 'test';
        $this->assertTrue($this->changed);
    }
    
    private $changed;
    
    public function changeListener($sender, $args){
        if($args[0] == 'title' && $args[1] == 'test'){
            $this->assertEquals($this->object, $sender);
            $this->changed = true;
        }
    }

    /**
     * @covers pModelWatcher::__set
     */
    public function test__set() {
        $msg = 'test title';
        $this->assertEmpty($this->model->title);
        $this->object->title = $msg;
        $this->assertEquals($msg, $this->model->title);
    }

    /**
     * @covers pModelWatcher::__get
     */
    public function test__get() {
        $msg = 'test title';
        $this->assertEmpty($this->object->title);
        $this->model->title = $msg;
        $this->assertEquals($msg, $this->object->title);
    }

    /**
     * @covers pModelWatcher::__isset
     */
    public function test__isset() {
        $msg = 'test title';
        $this->assertFalse(isset($this->object->title));
        $this->model->title = $msg;
        $this->assertTrue(isset($this->object->title));
    }

    /**
     * @covers pModelWatcher::__unset
     */
    public function test__unset() {
        $msg = 'test title';
        $this->model->title = $msg;
        $this->assertTrue(isset($this->object->title));
        unset($this->object->title);
        $this->assertFalse(isset($this->object->title));
    }

    /**
     * @covers pModelWatcher::__call
     */
    public function test__call() {
        $this->assertFalse($this->model->call);
        $this->object->call();
        $this->assertTrue($this->model->call);
    }

}