<?php
namespace Packfire\Event;

/**
 * Test class for EventHandler.
 * Generated by PHPUnit on 2012-07-06 at 04:58:15.
 */
class EventHandlerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EventHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EventHandler($this);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers EventHandler::on
     * @covers EventHandler::trigger
     */
    public function testCombined() {
        $this->object->on('click', function($obj, $arg = null){
            $obj->assertNull($arg);
            $obj->assertInstanceOf('\PHPUnit_Framework_TestCase', $obj);
        });
        $this->object->trigger('click');
    }
}