<?php

pload('packfire.datetime.pTimer');

/**
 * Test class for pTimer.
 * Generated by PHPUnit on 2012-04-28 at 02:31:42.
 */
class pTimerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pTimer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pTimer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * 
     */
    public function testTimer() {
        try{
            $this->object->result(); // should throw exception
            $this->assertTrue(false);
        }catch(Exception $ex){
            $this->assertInstanceOf('pInvalidRequestException', $ex);
        }
        $this->object->start();
        try{
            $this->object->start(); // should throw exception
            $this->assertTrue(false);
        }catch(Exception $ex){
            $this->assertInstanceOf('pInvalidRequestException', $ex);
        }
        $this->assertTrue($this->object->running());
        usleep(10);
        $this->assertTrue($this->object->result() > 0);
        $this->assertTrue($this->object->running());
        $stop = $this->object->stop();
        $this->assertFalse($this->object->running());
        $this->assertTrue($stop > 0);
        $this->assertEquals($stop, $this->object->result());
        $this->object->reset();
        $this->assertFalse($this->object->running());
        try{
            $this->object->result(); // should throw exception
            $this->assertTrue(false);
        }catch(Exception $ex){
            $this->assertInstanceOf('pInvalidRequestException', $ex);
        }
    }

}