<?php
namespace Packfire\DateTime;

/**
 * Test class for Timer.
 * Generated by PHPUnit on 2012-04-28 at 02:31:42.
 */
class TimerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\DateTime\Timer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @covers \Packfire\DateTime\Timer::__construct
     */
    protected function setUp()
    {
        $this->object = new Timer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @expectedException \Packfire\Exception\InvalidRequestException
     */
    public function testResultFail()
    {
        $this->object->result(); // should throw exception
    }

    /**
     * @expectedException \Packfire\Exception\InvalidRequestException
     */
    public function testResultFail2()
    {
        $this->object->start();
        $this->object->stop();
        $this->object->reset();
        $this->object->result(); // should throw exception
    }

    /**
     * @expectedException \Packfire\Exception\InvalidRequestException
     */
    public function testStartFail()
    {
        $this->object->start();
        $this->object->start();
    }

    /**
     * @covers \Packfire\DateTime\Timer
     */
    public function testTimer()
    {
        $this->object->start();
        $this->assertTrue($this->object->running());
        usleep(10);
        $this->assertTrue($this->object->result() > 0);
        $this->assertTrue($this->object->running());
        $stop = $this->object->stop();
        $this->assertFalse($this->object->running());
        $this->assertTrue($stop > 0);
        $this->assertEquals($stop, $this->object->result());
    }

}
