<?php

pload('packfire.yaml.pYaml');

/**
 * Test class for pYaml.
 * Generated by PHPUnit on 2012-09-30 at 01:24:47.
 */
class pYamlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pYaml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $text = new pTextStream("---\ntest:true\n...");
        $this->object = new pYaml($text);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pYaml::read
     */
    public function testRead() {
        $result = $this->object->read();
        $this->assertInternalType('array', $result);
        $this->assertCount(1, $result);
        $this->assertEquals(array('test' => true), $result);
    }

    /**
     * @covers pYaml::parser
     */
    public function testParser() {
        $this->assertInstanceof('pYamlParser', $this->object->parser());
    }

}
