<?php

pload('packfire.yaml.pYamlParser');
pload('packfire.io.pStreamReader');
pload('packfire.text.pTextStream');

/**
 * Test class for pYamlParser.
 * Generated by PHPUnit on 2012-07-12 at 19:33:57.
 */
class pYamlParserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pYamlParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    private function createParser($text){
        if(is_file($text)){
            $text = new pFileStream($text);
        }else{
            $text = new pTextStream($text);
        }
        $parser = new pYamlParser(new pStreamReader($text));
        $parser->findDocumentStart();
        return $parser;
    }
    
    /**
     * @covers pYamlParser::parse
     */
    public function testParse() {
        $object = $this->createParser('files/sample1.yml');
        $result = $object->parse();
        $this->assertInternalType('array', $result);
        $this->assertCount(5, $result);
    }

    /**
     * @covers pYamlParser::findDocumentStart
     * @todo Implement testFindDocumentStart().
     */
    public function testFindDocumentStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}