<?php

pload('packfire.yaml.pYamlPart');

/**
 * Test class for pYamlPart.
 * Generated by PHPUnit on 2012-09-30 at 01:27:36.
 */
class pYamlPartTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pYamlPart::quotationMarkers
     */
    public function testClass() {
        $this->assertEquals('---', pYamlPart::DOC_START);
        $this->assertEquals('...', pYamlPart::DOC_END);
        $this->assertEquals(':', pYamlPart::KEY_VALUE_SEPARATOR);
        $this->assertEquals('- ', pYamlPart::SEQUENCE_ITEM_BULLET);
        $this->assertEquals("-\n", pYamlPart::SEQUENCE_ITEM_BULLET_EMPTYLINE);
        $this->assertEquals(array('"', '\''), pYamlPart::quotationMarkers());
    }

}
