<?php

pload('packfire.yaml.pYamlInline');

/**
 * Test class for pYamlInline.
 * Generated by PHPUnit on 2012-07-13 at 06:26:32.
 */
class pYamlInlineTest extends PHPUnit_Framework_TestCase {


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pYamlInline::parseValue
     */
    public function testParseValue() {
        $this->assertEquals('test two', pYamlInline::load('test two')->parseValue());
        $pos = 0;
        $this->assertEquals('test', pYamlInline::load('test two')->parseValue($pos, array(' ')));
        $this->assertEquals(5, $pos);
        $this->assertEquals('two', pYamlInline::load('test two')->parseValue($pos));
        $pos = 0;
        $this->assertEquals('test two', pYamlInline::load('"test two"')->parseValue($pos, array(' ')));
    }

    /**
     * @covers pYamlInline::parseKeyValue
     */
    public function testParseKeyValue() {
        $data = pYamlInline::load('test: alpha')->parseKeyValue();
        $this->assertEquals(array('test' => 'alpha'), $data);
        $data = pYamlInline::load('test: "alpha: is happy"')->parseKeyValue();
        $this->assertEquals(array('test' => 'alpha: is happy'), $data);
    }

    /**
     * @covers pYamlInline::parseSequence
     */
    public function testParseSequence() {
        $data = pYamlInline::load('[test, 1, 2, "{maybe, cool]", three]')->parseSequence();
        $this->assertEquals(array('test', 1, 2, '{maybe, cool]', 'three'), $data);
    }

    /**
     * @covers pYamlInline::parseMap
     */
    public function testParseMap() {
        $data = pYamlInline::load('{alpha: test, mike: bravo, good: "bad}, equals", hungry: "yes[iam"}')->parseMap();
        $this->assertEquals(array(
            'alpha' => 'test',
            'mike' => 'bravo',
            'good' => 'bad}, equals',
            'hungry' => 'yes[iam'
        ), $data);
    }

}