<?php
namespace Packfire\Yaml;

/**
 * Test class for YamlPart.
 * Generated by PHPUnit on 2012-09-30 at 01:27:36.
 */
class YamlPartTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Packfire\Yaml\YamlPart::quotationMarkers
     */
    public function testClass() {
        $this->assertEquals('---', YamlPart::DOC_START);
        $this->assertEquals('...', YamlPart::DOC_END);
        $this->assertEquals(':', YamlPart::KEY_VALUE_SEPARATOR);
        $this->assertEquals('- ', YamlPart::SEQUENCE_ITEM_BULLET);
        $this->assertEquals("-\n", YamlPart::SEQUENCE_ITEM_BULLET_EMPTYLINE);
        $this->assertEquals(array('"', '\''), YamlPart::quotationMarkers());
    }

}
