<?php

pload('packfire.plinq.pLinqJoinQuery');

/**
 * Test class for pLinqJoinQuery.
 * Generated by PHPUnit on 2012-09-18 at 03:44:31.
 */
class pLinqJoinQueryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pLinqJoinQuery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $data = array(
            array('key' => 1, 'name' => 'Ridge'),
            array('key' => 2, 'name' => 'Yong')
        );
        $this->object = new pLinqJoinQuery($data, function($x){return $x['foreign'];}, function($x){return $x['key'];}, function($a, $b){return $a['name'] . ' ' . $b['name'];});
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pLinqJoinQuery::run
     */
    public function testRun() {
        $collection = array(
            array('key' => 1, 'name' => 'Sam', 'foreign' => 2),
            array('key' => 2, 'name' => 'Kent', 'foreign' => 1)
        );
        $result = $this->object->run($collection);
        $this->assertEquals(array('Sam Yong', 'Kent Ridge'), $result);
    }

}