<?php

pload('packfire.io.file.pFileStream');
pload('packfire.io.file.pFile');

/**
 * Test class for pFileStream.
 * Generated by PHPUnit on 2012-07-16 at 13:42:46.
 */
class pFileStreamTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pFileStream
     */
    protected $object;
    
    /**
     *
     * @var pFile
     */
    protected $file;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $file = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'tempFile';
        $this->file = new pFile($file);
        $this->file->create();
        $this->object = new pFileStream($file);
        $this->object->open();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object->close();
        $this->file->delete();
    }

    /**
     * @covers pFileStream::flush
     */
    public function testFlush() {
        $this->assertTrue(method_exists('pFileStream', 'flush'));
    }

    /**
     * @covers pFileStream::write
     */
    public function testWrite() {
        $this->object->write('test');
        $this->assertEquals('test', file_get_contents($this->file->pathname()));
    }

}