<?php
namespace Packfire\IO\File;

/**
 * Test class for Stream.
 * Generated by PHPUnit on 2012-07-16 at 13:42:46.
 */
class StreamTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\IO\File\Stream
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $file = 'php://temp';
        $this->object = new Stream($file);
        $this->object->open();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object->close();
    }

    /**
     * @covers \Packfire\IO\File\Stream::flush
     */
    public function testFlush()
    {
        $this->assertTrue(method_exists('Packfire\IO\File\Stream', 'flush'));
    }

    /**
     * @covers \Packfire\IO\File\Stream::write
     */
    public function testWrite()
    {
        $this->object->write('test');
        $this->object->seek(0);
        $this->assertEquals('test', $this->object->read(4));
    }
}
