<?php

pload('packfire.data.serialization.pPhpSerializer');
pload('packfire.text.pTextStream');

/**
 * Test class for pPhpSerializer.
 * Generated by PHPUnit on 2012-06-13 at 09:41:16.
 */
class pPhpSerializerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pPhpSerializer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pPhpSerializer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pPhpSerializer::serialize
     */
    public function testSerialize() {
        $data = array('key' => 'value', 'test');
        $stream = new pTextStream();
        $this->object->serialize($stream, $data);
        $stream->seek(0);
        $this->assertEquals(serialize($data), $stream->read($stream->length()));
    }

    /**
     * @covers pPhpSerializer::serialize
     */
    public function testSerialize2() {
        $data = new stdClass();
        $data->test = 'data';
        $data->control = array('date' => true);
        $stream = new pTextStream();
        $this->object->serialize($stream, $data);
        $stream->seek(0);
        $this->assertEquals(serialize($data), $stream->read($stream->length()));
    }

    /**
     * @covers pPhpSerializer::serialize
     */
    public function testSerialize3() {
        $data = new stdClass();
        $data->test = 'data';
        $data->control = array('date' => true);
        $result = $this->object->serialize($data);
        $this->assertEquals(serialize($data), $result);
    }

    /**
     * @covers pPhpSerializer::deserialize
     */
    public function testDeserialize() {
        $data = array('key' => 'value', 'test');
        $stream = new pTextStream(serialize($data));
        $item = $this->object->deserialize($stream);
        $this->assertEquals($data, $item);
    }

    /**
     * @covers pPhpSerializer::deserialize
     */
    public function testDeserialize2() {
        $data = new stdClass();
        $data->test = 'data';
        $data->control = array('date' => true);
        $stream = new pTextStream(serialize($data));
        $item = $this->object->deserialize($stream);
        $this->assertEquals($data, $item);
    }

    /**
     * @covers pPhpSerializer::deserialize
     */
    public function testDeserialize3() {
        $data = new stdClass();
        $data->test = 'data';
        $data->control = array('date' => true);
        $result = $this->object->deserialize(serialize($data));
        $this->assertEquals($data, $result);
    }
    
    public function testOverall(){
        $data = new stdClass();
        $data->test = 'data';
        $data->control = array('date' => true);
        $item = $this->object->deserialize($this->object->serialize($data));
        $this->assertEquals($data, $item);
    }

}