<?php

pload('packfire.ioc.pServiceInjector');
require_once('mocks/tMockConfig.php');
require_once('mocks/tMockBucketUser.php');

/**
 * Test class for pServiceInjector.
 * Generated by PHPUnit on 2012-08-07 at 07:35:39.
 */
class pServiceInjectorTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pServiceInjector::inject
     */
    public function testInject() {
        $user = new tMockBucketUser();
        $user->setBucket(new pServiceBucket());
        $object = new pServiceInjector($user);
        $testObj = new tMockConfig();
        $object->inject('test', $testObj);
        $this->assertInstanceOf('tMockConfig', $user->service('test'));
        $this->assertEquals($testObj, $user->service('test'));
    }

    /**
     * @covers pServiceInjector::inject
     */
    public function testInject2() {
        $bucket = new pServiceBucket();
        $object = new pServiceInjector($bucket);
        $testObj = new tMockConfig();
        $object->inject('test', $testObj);
        $this->assertInstanceOf('tMockConfig', $bucket->pick('test'));
        $this->assertEquals($testObj, $bucket->pick('test'));
    }

}
