<?php
namespace Packfire\IoC;

/**
 * Test class for ServiceBucket.
 * Generated by PHPUnit on 2012-06-29 at 00:59:56.
 */
class ServiceBucketTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ServiceBucket
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ServiceBucket;
        $this->object->put('test', $this);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers ServiceBucket::__call
     */
    public function test__call() {
        $this->assertInstanceOf('Packfire\IoC\ServiceBucketTest', $this->object->testService());
        $this->assertNull($this->object->nullService());
    }

    /**
     * @covers ServiceBucket::put
     * @covers ServiceBucket::pick
     */
    public function testPutPick() {
        $this->object->put('break', function(){return new \stdClass();});
        $this->assertInstanceOf('\stdClass', $this->object->pick('break'));
        $this->object->put('bend', array($this, 'load'));
        $this->assertInstanceOf('stdClass', $this->object->pick('bend'));
    }

    public function load(){
        return new \stdClass();
    }

    /**
     * @covers ServiceBucket::contains
     */
    public function testContains() {
        $this->assertTrue($this->object->contains('test'));
        $this->assertFalse($this->object->contains('null'));
    }

}