<?php
namespace Packfire;

/**
 * Test class for Packfire.
 * Generated by PHPUnit on 2012-12-09 at 01:46:02.
 */
class PackfireTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Packfire\Packfire
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Packfire();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Packfire::classLoader()
     */
    public function testClassLoader(){
        $classLoader = $this->object->classLoader();
        $this->assertInstanceOf('\\Packfire\\Core\\ClassLoader\\ClassLoader', $classLoader);
    }

}