<?php
namespace Packfire\Linq;

/**
 * Test class for OrderedLinq.
 * Generated by PHPUnit on 2012-10-12 at 08:15:28.
 */
class OrderedLinqTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var OrderedLinq
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new OrderedLinq(array(
            array('i' => 5, 'r' => 3),
            array('i' => 2, 'r' => 5),
            array('i' => 2, 'r' => 1),
            array('i' => 3, 'r' => 8)
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Packfire\Linq\OrderedLinq::thenBy
     */
    public function testThenBy() {
        $this->object->orderBy(function($x){return $x['i'];});
        $this->object->thenBy(function($x){return $x['r'];});
        $list = $this->object->toList();
        $this->assertCount(4, $list);
        $this->assertEquals(array('i' => 2, 'r' => 1), $list[0]);
        $this->assertEquals(array('i' => 2, 'r' => 5), $list[1]);
        $this->assertEquals(array('i' => 3, 'r' => 8), $list[2]);
        $this->assertEquals(array('i' => 5, 'r' => 3), $list[3]);
    }

    /**
     * @covers Packfire\Linq\OrderedLinq::thenByDesc
     */
    public function testThenByDesc() {
        $this->object->orderBy(function($x){return $x['i'];});
        $this->object->thenByDesc(function($x){return $x['r'];});
        $list = $this->object->toList();
        $this->assertCount(4, $list);
        $this->assertEquals(array('i' => 2, 'r' => 5), $list[0]);
        $this->assertEquals(array('i' => 2, 'r' => 1), $list[1]);
        $this->assertEquals(array('i' => 3, 'r' => 8), $list[2]);
        $this->assertEquals(array('i' => 5, 'r' => 3), $list[3]);
    }

}

?>
