<?php

pload('packfire.collection.pQueue');

/**
 * Test class for pQueue.
 * Generated by PHPUnit on 2012-02-19 at 05:16:55.
 */
class pQueueTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pQueue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pQueue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pQueue::enqueue
     */
    public function testEnqueue() {
        $this->assertCount(0, $this->object);
        $this->object->enqueue(5);
        $this->assertCount(1, $this->object);
        $this->assertEquals(5, $this->object->front());
        $this->object->enqueue(2);
        $this->assertCount(2, $this->object);
        $this->assertEquals(5, $this->object->front());
    }

    /**
     * @covers pQueue::dequeue
     */
    public function testDequeue() {
        $this->object->enqueue(5);
        $this->assertCount(1, $this->object);
        $this->object->enqueue(2);
        $this->assertCount(2, $this->object);
        $this->assertEquals(5, $this->object->dequeue());
        $this->assertCount(1, $this->object);
        $this->assertEquals(2, $this->object->dequeue());
        $this->assertCount(0, $this->object);
    }

    /**
     * @covers pQueue::front
     */
    public function testFront() {
        $this->object->enqueue(5);
        $this->assertEquals(5, $this->object->front());
        $this->object->enqueue(2);
        $this->assertEquals(5, $this->object->front());
    }

}