<?php
namespace Packfire\Collection;

/**
 * Test class for Stack.
 * Generated by PHPUnit on 2012-02-19 at 05:16:53.
 */
class StackTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Collection\Stack
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Stack;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Collection\Stack::push
     */
    public function testPush()
    {
        $this->assertCount(0, $this->object);
        $this->object->push(10);
        $this->assertCount(1, $this->object);
        $this->object->push(3);
        $this->assertCount(2, $this->object);
        $this->object->push(5);
        $this->assertCount(3, $this->object);
    }

    /**
     * @covers \Packfire\Collection\Stack::pop
     */
    public function testPop()
    {
        $this->object->push(10);
        $this->object->push(3);
        $this->object->push(5);
        $this->assertCount(3, $this->object);

        $this->assertEquals(5, $this->object->pop());
        $this->assertCount(2, $this->object);
        $this->assertEquals(3, $this->object->pop());
        $this->assertCount(1, $this->object);
        $this->assertEquals(10, $this->object->pop());
        $this->assertCount(0, $this->object);

    }

    /**
     * @covers \Packfire\Collection\Stack::top
     */
    public function testTop()
    {
        $this->object->push(10);
        $this->assertEquals(10, $this->object->top());
        $this->object->push(3);
        $this->assertEquals(3, $this->object->top());
        $this->object->push(5);
        $this->assertEquals(5, $this->object->top());
    }

}
