<?php
namespace Packfire\Template\Mustache;

/**
 * Test class for Mustache.
 * Generated by PHPUnit on 2012-09-19 at 05:09:54.
 */
class MustacheTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Packfire\Template\Mustache\Mustache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Mustache('Hello {{name}}{{#intro}}, my name is {{intro}}{{/intro}}!');
        $this->object->parameters(array('name' => 'world'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Packfire\Template\Mustache\Mustache::template
     */
    public function testTemplate() {
        $this->object->template('Good day {{name}}!');
        $this->assertEquals('Good day world!', $this->object->render());
    }

    /**
     * @covers \Packfire\Template\Mustache\Mustache::parameters
     */
    public function testParameters() {
        $this->object->parameters(array('name' => 'Jack', 'intro' => 'Jill'));
        $this->assertEquals('Hello Jack, my name is Jill!', $this->object->render());
    }

    /**
     * @covers \Packfire\Template\Mustache\Mustache::render
     */
    public function testRender() {
        $this->assertEquals('Hello world!', $this->object->render());
    }

}