<?php

pload('packfire.application.cli.pCommandRequest');

/**
 * Test class for pCommandRequest.
 * Generated by PHPUnit on 2012-07-16 at 13:15:18.
 */
class pCommandRequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pCommandRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pCommandRequest(array('script.php', '-at', '--beta'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pCommandRequest::params
     */
    public function testParams() {
        $this->assertInstanceOf('IAppRequest', $this->object);
        $this->assertEquals(array(
            'script.php',
            'a' => true,
            't' => true,
            'beta' => true
        ), $this->object->params()->toArray());
    }

}