<?php
namespace Packfire\Application;

use Packfire\IoC\ServiceBucket;

/**
 * Test class for ServiceAppLoader.
 * Generated by PHPUnit on 2012-07-16 at 13:01:33.
 */
class ServiceAppLoaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ServiceAppLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ServiceAppLoader(new ServiceBucket());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers ServiceAppLoader::load
     */
    public function testLoad(){
        $this->object->load();
        $this->assertTrue($this->object->contains('config.app'));
        $this->assertFalse($this->object->contains('config.routing'));
    }

}