<?php
namespace Packfire\Config\Driver;

/**
 * Test class for IniConfig.
 * Generated by PHPUnit on 2012-07-14 at 05:40:58.
 */
class IniConfigTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IniConfig
     */
    protected $object;
    
    private $file = 'test/Files/sampleConfig.ini';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $this->getMock('\\Packfire\\Config\\Driver\\IniConfig', array('read'), array($this->file));
        
        $property = new \ReflectionProperty($this->object, 'data');
        $property->setAccessible(true);
        $data = array(
            'first_section' => array(
                'one' => 1,
                'five' => 5,
                'animal' => 'BIRD'
            ),
            'second_section' => array(
                'path' => '/usr/local/bin',
                'URL' => 'http://www.example.com/~username'
            ),
            'third_section' => array(
                'phpversion' => array(
                    '5.0',
                    '5.1',
                    '5.2',
                    '5.3'
                )
            )
        );
        $property->setValue($this->object, $data);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function testParseConfig(){
        $this->assertNotNull($this->object->get('first_section'));
        $this->assertNotNull($this->object->get('second_section'));
        $this->assertNotNull($this->object->get('third_section'));
        $this->assertCount(3, $this->object->get());

        $this->assertEquals(1, $this->object->get('first_section', 'one'));
        $this->assertEquals('BIRD', $this->object->get('first_section', 'animal'));

        $this->assertEquals(array(
            'path' => '/usr/local/bin',
            'URL' => 'http://www.example.com/~username'
        ), $this->object->get('second_section'));

        $this->assertCount(4, $this->object->get('third_section', 'phpversion'));
    }

}