<?php

namespace Packfire\Config\Driver;

require_once(__DIR__ . '/ConfigTestSetter.php');

/**
 * Test class for IniConfig.
 * Generated by PHPUnit on 2012-07-14 at 05:40:58.
 */
class IniConfigTest extends ConfigTestSetter {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @covers \Packfire\Config\Driver\IniConfig::read
     */
    protected function setUp() {
        $this->prepare('\\Packfire\\Config\\Driver\\IniConfig');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

}