<?php

pload('packfire.application.http.phttpServiceBucket');
pload('packfire.ioc.pServiceBucket');

/**
 * Test class for pHttpServiceBucket.
 * Generated by PHPUnit on 2012-09-17 at 07:27:54.
 */
class pHttpServiceBucketTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pHttpServiceBucket
     */
    protected $object;
    
    /**
     *
     * @var pServiceBucket 
     */
    protected $bucket;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->bucket = new pServiceBucket();
        $this->object = new pHttpServiceBucket($this->bucket);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pHttpServiceBucket::load
     */
    public function testLoad() {
        $this->object->load();
        $this->assertTrue($this->bucket->contains('config.routing'));
        $this->assertInstanceOf('pHttpRouter', $this->bucket->pick('router'));        
    }

}
