<?php
namespace Packfire\Session;

use Packfire\IoC\ServiceBucket;

/**
 * Test class for Loader.
 * Generated by PHPUnit on 2012-09-19 at 05:28:12.
 */
class LoaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Loader
     */
    protected $object;

    /**
     *
     * @var ServiceBucket
     */
    protected $bucket;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->bucket = new ServiceBucket();
        $this->object = new Loader($this->bucket);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Loader::load
     */
    public function testLoad() {
        $this->object->load();
        $this->assertTrue($this->bucket->contains('session.storage'));
        $this->assertInstanceOf('Packfire\Session\Session', $this->bucket->pick('session'));
    }

}
