<?php

pload('packfire.session.pSession');
pload('packfire.session.pSessionLoader');
pload('packfire.ioc.pServiceBucket');

/**
 * Test class for pSessionLoader.
 * Generated by PHPUnit on 2012-09-19 at 05:28:12.
 */
class pSessionLoaderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pSessionLoader
     */
    protected $object;

    /**
     *
     * @var pServiceBucket 
     */
    protected $bucket;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->bucket = new pServiceBucket();
        $this->object = new pSessionLoader($this->bucket);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pSessionLoader::load
     */
    public function testLoad() {
        $this->object->load();
        $this->assertTrue($this->bucket->contains('session.storage'));
        $this->assertInstanceOf('pSession', $this->bucket->pick('session'));
    }

}
