<?php
namespace Packfire\OAuth;

/**
 * Test class for Signature.
 * Generated by PHPUnit on 2012-09-26 at 08:04:17.
 */
class SignatureTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\OAuth\Signature::load
     */
    public function testLoad()
    {
        $class = Signature::load('HMAC-SHA1');
        $this->assertEquals('Packfire\OAuth\Signature\HmacSha1', $class);
    }

    /**
     * @covers \Packfire\OAuth\Signature::load
     */
    public function testLoad2()
    {
        $class = Signature::load('PLAINTEXT');
        $this->assertEquals('Packfire\OAuth\Signature\PlainText', $class);
    }

    /**
     * @covers \Packfire\OAuth\Signature::load
     */
    public function testLoadFail()
    {
        $this->assertNull(Signature::load('WOAHFAIL'));
    }

    /**
     * @covers \Packfire\OAuth\Signature::check
     */
    public function testCheck()
    {
        $stub = $this->getMockForAbstractClass('Packfire\OAuth\Signature', array(), '', false);
        $stub->expects($this->exactly(2))
                ->method('build')
                ->will($this->returnValue('test'));
        $this->assertTrue($stub->check('test'));
        $this->assertFalse($stub->check('test2'));
    }

}
