<?php

pload('packfire.debugger.firebug.pFirebugDebugOutput');

/**
 * Test class for pFirebugDebugOutput.
 * Generated by PHPUnit on 2012-09-30 at 02:03:42.
 */
class pFirebugDebugOutputTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pFirebugDebugOutput
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pFirebugDebugOutput;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pFirebugDebugOutput::output
     */
    public function testOutput() {
        ob_start();
        $this->object->output();
        $content = ob_get_clean();
        $this->assertEquals('', $content);
    }

    /**
     * @covers pFirebugDebugOutput::write
     * @todo Implement testWrite().
     */
    public function testWrite() {
        $this->object->write('test');
        ob_start();
        $this->object->output();
        $content = ob_get_clean();
        $this->assertTrue(strpos($content,
                'console.log("test");') > 0);
    }

}