<?php
namespace Packfire\Welcome;

/**
 * Test class for HelloWorldView.
 * Generated by PHPUnit on 2012-09-03 at 04:07:02.
 */
class HelloWorldViewTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Welcome\HelloWorldView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HelloWorldView;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Welcome\HelloWorldView::render()
     */
    public function testRender()
    {
        $content = $this->object->render();
        $this->assertEquals('Hello World', $content);
    }
}
