<?php

pload('packfire.security.pSecurityModule');

/**
 * Test class for pSecurityModule.
 * Generated by PHPUnit on 2012-04-07 at 08:37:23.
 */
class pSecurityModuleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pSecurityModule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pSecurityModule();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pSecurityModule::authenticate
     */
    public function testAuthenticate() {
        $this->assertTrue($this->object->authenticate(null));
    }

    /**
     * @covers pSecurityModule::authorize
     */
    public function testAuthorize() {
        $this->assertTrue($this->object->authorize(null));
    }

    /**
     * @covers pSecurityModule::identity
     */
    public function testIdentity() {
        $this->assertNull($this->object->identity(null));
        $this->assertNull($this->object->identity());
        $this->assertEquals('sam', $this->object->identity('sam'));
    }

    /**
     * @covers pSecurityModule::deauthenticate
     */
    public function testDeauthenticate() {
        $this->assertTrue(method_exists($this->object, 'deauthenticate'));
    }

}
