<?php
namespace Packfire\Security;

/**
 * Test class for SecurityModule.
 * Generated by PHPUnit on 2012-04-07 at 08:37:23.
 */
class SecurityModuleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Security\SecurityModule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SecurityModule();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Security\SecurityModule::authenticate
     */
    public function testAuthenticate()
    {
        $this->assertTrue($this->object->authenticate(null));
    }

    /**
     * @covers \Packfire\Security\SecurityModule::authorize
     */
    public function testAuthorize()
    {
        $this->assertTrue($this->object->authorize(null));
    }

    /**
     * @covers \Packfire\Security\SecurityModule::identity
     */
    public function testIdentity()
    {
        $this->assertNull($this->object->identity(null));
        $this->assertNull($this->object->identity());
        $this->assertEquals('sam', $this->object->identity('sam'));
    }

    /**
     * @covers \Packfire\Security\SecurityModule::deauthenticate
     */
    public function testDeauthenticate()
    {
        $this->assertTrue(method_exists($this->object, 'deauthenticate'));
    }

    /**
     * @covers \Packfire\Security\SecurityModule::request
     */
    public function testRequest()
    {
        $this->assertNull($this->object->request());
        $this->assertEquals('test', $this->object->request('test'));
        $this->assertEquals('test', $this->object->request());
    }
}
