<?php
namespace Packfire\Linq\Query;

/**
 * Test class for Distinct.
 * Generated by PHPUnit on 2012-09-17 at 08:17:10.
 */
class DistinctTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Linq\Query\Distinct
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Distinct;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Linq\Query\Distinct::run
     */
    public function testRun()
    {
        $collection = array(5, 5, 2, 3, 5, 1, 2, 6);
        $this->assertEquals(array(0 => 5, 2 => 2, 3 => 3, 5 => 1, 7 => 6), $this->object->run($collection));
    }

    /**
     * @covers \Packfire\Linq\Query\Distinct::run
     */
    public function testRun2()
    {
        $collection = array(5, 5, 2, 3, 5, 1, 2, 6);
        $this->assertEquals(array(5, 2, 3, 1, 6), array_values($this->object->run($collection)));
    }
}
