<?php
namespace Packfire\Linq\Query;

/**
 * Test class for Reverse.
 * Generated by PHPUnit on 2012-09-18 at 07:08:37.
 */
class ReverseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Linq\Query\Reverse
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Packfire\Linq\Query\Reverse;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Linq\Query\Reverse::run
     */
    public function testRun()
    {
        $data = array('a', 'c', 'd', 'b', 'z');
        $this->assertEquals(array_reverse($data), $this->object->run($data));
    }

}
