<?php
namespace Packfire\Linq\Query;

/**
 * Test class for Select.
 * Generated by PHPUnit on 2012-09-18 at 07:17:29.
 */
class SelectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Linq\Query\Select
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Select(
            function ($x) {
                return $x * 3;
            }
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Linq\Query\Select::run
     */
    public function testRun()
    {
        $data = array(3, 5, 8, 6, 2);
        $result = $this->object->run($data);
        $this->assertEquals(array(9, 15, 24, 18, 6), $result);
    }
}
