<?php
namespace Packfire\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-24 at 06:24:31.
 */
class ErrorExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ErrorException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ErrorException('Test Error');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Packfire\Exception\ErrorException::setCode
     */
    public function testSetCode()
    {
        $value = 305;
        $this->object->setCode($value);
        $this->assertEquals($value, $this->object->getCode());
    }

    /**
     * @covers Packfire\Exception\ErrorException::setLine
     */
    public function testSetLine()
    {
        $value = 223;
        $this->object->setLine($value);
        $this->assertEquals($value, $this->object->getLine());
    }

    /**
     * @covers Packfire\Exception\ErrorException::setFile
     */
    public function testSetFile()
    {
        $value = 'make/test.php';
        $this->object->setFile($value);
        $this->assertEquals($value, $this->object->getFile());
    }
}
