<?php
namespace Packfire\Validator;

/**
 * Test class for EmailValidator.
 * Generated by PHPUnit on 2012-09-24 at 04:56:15.
 */
class EmailValidatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Packfire\Validator\EmailValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EmailValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Packfire\Validator\EmailValidator::validate
     */
    public function testValidate(){
        $this->assertTrue($this->object->validate('test@gmail.com'));
        $this->assertTrue($this->object->validate('green@goearth.co.uk'));
        $this->assertFalse($this->object->validate('example.co.uk'));
        $this->assertFalse($this->object->validate('test'));
    }

}