<?php
namespace Packfire\Validator;

/**
 * Test class for NumericValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:13:52.
 */
class NumericValidatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Packfire\Validator\NumericValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NumericValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Packfire\Validator\NumericValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate(0.5));
        $this->assertTrue($this->object->validate('0.5'));
        $this->assertTrue($this->object->validate(5));
        $this->assertFalse($this->object->validate('test'));
        $this->assertFalse($this->object->validate(true));
    }

}