<?php

pload('packfire.validator.pCallbackValidator');

/**
 * Test class for pCallbackValidator.
 * Generated by PHPUnit on 2012-09-23 at 01:21:50.
 */
class pCallbackValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pCallbackValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pCallbackValidator(function($value) {
                            return $value === 5;
                        });
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pCallbackValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate(5));
        $this->assertFalse($this->object->validate('5'));
    }

}