<?php

pload('packfire.validator.pCheckboxValidator');

/**
 * Test class for pCheckboxValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:50:21.
 */
class pCheckboxValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pCheckboxValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pCheckboxValidator(false);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pCheckboxValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate(false));
        $this->assertFalse($this->object->validate(true));
    }

}