<?php

pload('packfire.validator.pEmailValidator');

/**
 * Test class for pEmailValidator.
 * Generated by PHPUnit on 2012-09-24 at 04:56:15.
 */
class pEmailValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pEmailValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pEmailValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testValidate(){
        $this->assertTrue($this->object->validate('test@gmail.com'));
        $this->assertTrue($this->object->validate('green@goearth.co.uk'));
        $this->assertFalse($this->object->validate('example.co.uk'));
        $this->assertFalse($this->object->validate('test'));
    }

}