<?php

pload('packfire.validator.pMatchValidator');

/**
 * Test class for pMatchValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:41:07.
 */
class pMatchValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pMatchValidator::validate
     */
    public function testValidate() {
        $object = new pMatchValidator(array('a', 'b', 'c'));
        $this->assertTrue($object->validate('b'));
        $this->assertTrue($object->validate('c'));
        $this->assertFalse($object->validate('z'));
        $this->assertFalse($object->validate('h'));
    }

    /**
     * @covers pMatchValidator::validate
     */
    public function testValidate2() {
        $object = new pMatchValidator(new pList(array('a', 'b', 'c')));
        $this->assertTrue($object->validate('b'));
        $this->assertTrue($object->validate('c'));
        $this->assertFalse($object->validate('z'));
        $this->assertFalse($object->validate('h'));
    }

    /**
     * @covers pMatchValidator::validate
     */
    public function testValidate3() {
        $object = new pMatchValidator(5);
        $this->assertTrue($object->validate(5));
        $this->assertFalse($object->validate(2));
    }

}
