<?php

pload('packfire.validator.pNumericRangeValidator');

/**
 * Test class for pNumericRangeValidator.
 * Generated by PHPUnit on 2012-09-22 at 13:36:17.
 */
class pNumericRangeValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pNumericRangeValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pNumericRangeValidator(50, 250);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pNumericRangeValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate(50));
        $this->assertTrue($this->object->validate(60));
        $this->assertTrue($this->object->validate(150));
        $this->assertTrue($this->object->validate(220));
        $this->assertTrue($this->object->validate(250));
        
        $this->assertFalse($this->object->validate(49));
        $this->assertFalse($this->object->validate(251));
        $this->assertFalse($this->object->validate(20));
        $this->assertFalse($this->object->validate(1000));
    }

}