<?php

pload('packfire.validator.pRegexValidator');

/**
 * Test class for pRegexValidator.
 * Generated by PHPUnit on 2012-09-22 at 13:33:37.
 */
class pRegexValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pRegexValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pRegexValidator('/(on|off)/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pRegexValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate('on'));
        $this->assertTrue($this->object->validate('off'));
        $this->assertFalse($this->object->validate('ON'));
        $this->assertFalse($this->object->validate('OFF'));
    }

}