<?php

pload('packfire.validator.pSerialValidator');
pload('packfire.validator.pDataTypeValidator');
pload('packfire.validator.pNumericRangeValidator');

/**
 * Test class for pSerialValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:51:47.
 */
class pSerialValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pSerialValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pSerialValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pSerialValidator::validate
     */
    public function testValidate() {
        $this->object->add(new pDataTypeValidator('double'));
        $this->object->add(new pNumericRangeValidator(100, 300));
        
        $this->assertTrue($this->object->validate(250.1));
        $this->assertFalse($this->object->validate('test'));
        $this->assertFalse($this->object->validate(250));
        $this->assertFalse($this->object->validate(1000.5));
    }

}