<?php

pload('packfire.validator.pStringLengthValidator');

/**
 * Test class for pStringLengthValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:19:27.
 */
class pStringLengthValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pStringLengthValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pStringLengthValidator(4);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pStringLengthValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate('test'));
        $this->assertFalse($this->object->validate('pit'));
        $this->assertFalse($this->object->validate('match'));
    }

}