<?php

pload('packfire.validator.pStringMaxLengthValidator');

/**
 * Test class for pStringMaxLengthValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:24:27.
 */
class pStringMaxLengthValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pStringMaxLengthValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pStringMaxLengthValidator(4);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pStringMaxLengthValidator::validate
     * @todo Implement testValidate().
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate('cave'));
        $this->assertTrue($this->object->validate('run'));
        $this->assertFalse($this->object->validate('light'));
        $this->assertFalse($this->object->validate('validates'));
    }

}