<?php
namespace Packfire\Validator;

/**
 * Test class for RegexValidator.
 * Generated by PHPUnit on 2012-09-22 at 13:33:37.
 */
class RegexValidatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Packfire\Validator\RegexValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RegexValidator('/(on|off)/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Packfire\Validator\RegexValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate('on'));
        $this->assertTrue($this->object->validate('off'));
        $this->assertFalse($this->object->validate('ON'));
        $this->assertFalse($this->object->validate('OFF'));
    }

}