<?php
namespace Packfire\Validator;

/**
 * Test class for SerialValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:51:47.
 */
class SerialValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Validator\SerialValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SerialValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Validator\SerialValidator::validate
     */
    public function testValidate()
    {
        $this->object->add(new DataTypeValidator('double'));
        $this->object->add(new NumericRangeValidator(100, 300));

        $this->assertTrue($this->object->validate(250.1));
        $this->assertFalse($this->object->validate('test'));
        $this->assertFalse($this->object->validate(250));
        $this->assertFalse($this->object->validate(1000.5));
    }
}
