<?php
namespace Packfire\Validator;

/**
 * Test class for StringLengthRangeValidator.
 * Generated by PHPUnit on 2012-09-22 at 14:17:15.
 */
class StringLengthRangeValidatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Packfire\Validator\StringLengthRangeValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StringLengthRangeValidator(4, 6);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Packfire\Validator\StringLengthRangeValidator::validate
     */
    public function testValidate() {
        $this->assertTrue($this->object->validate('test'));
        $this->assertTrue($this->object->validate('runner'));
        $this->assertFalse($this->object->validate('hello world'));
        $this->assertFalse($this->object->validate('arm'));
    }

}