<?php

pload('packfire.template.pTemplate');

/**
 * Test class for pTemplate.
 * Generated by PHPUnit on 2012-02-15 at 17:30:46.
 */
class pTemplateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pTemplate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pTemplate('{name}: {job} {date}');
    }
    
    function testConstants(){
        $this->assertEquals('}', pTemplate::KEY_CLOSE);
        $this->assertEquals('{', pTemplate::KEY_OPEN);
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pTemplate::fields
     */
    public function testFields() {
        $this->assertInstanceOf('pMap', $this->object->fields());
        $this->object->fields()->add('name', 'David HasHunch');
        $this->object->fields()->add('job', 'Scientist');
        $this->object->fields()->add('date', 'Monday');
        $this->assertInstanceOf('pMap', $this->object->fields());
    }

    /**
     * @covers pTemplate::parse
     */
    public function testParse() {
        $this->object->fields()->add('name', 'David HasHunch');
        $this->object->fields()->add('job', 'Scientist');
        $this->object->fields()->add('date', 'Monday');
        $result = $this->object->parse();
        $this->assertInternalType('string', $result);
        $this->assertEquals('David HasHunch: Scientist Monday', $result);
    }

}
