<?php

pload('packfire.config.pConfigFactory');

/**
 * Test class for pConfigFactory.
 * Generated by PHPUnit on 2012-07-14 at 06:35:54.
 */
class pConfigFactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pConfigFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pConfigFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pConfigFactory::load
     */
    public function testLoadIni() {
        $config = $this->object->load('files/sampleConfig.ini');
        $this->assertInstanceOf('pIniConfig', $config);
    }

    /**
     * @covers pConfigFactory::load
     */
    public function testLoadPhp() {
        $config = $this->object->load('files/sampleConfig.php');
        $this->assertInstanceOf('pPhpConfig', $config);
    }

    /**
     * @covers pConfigFactory::load
     */
    public function testLoadYaml() {
        $config = $this->object->load('files/sampleConfig.yml');
        $this->assertInstanceOf('pYamlConfig', $config);
    }

}