<?php
namespace Packfire\Core;

/**
 * Test class for ObjectObserver.
 * Generated by PHPUnit on 2012-08-04 at 03:00:58.
 */
class ObjectObserverTest extends \PHPUnit_Framework_TestCase
{
    public $title;

    public $call = false;

    public function call()
    {
        $this->call = true;
    }

    public static function callStatic()
    {
        return 'test';
    }

    /**
     * @var \Packfire\Core\ObjectObserver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ObjectObserver($this);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Core\ObjectObserver::model
     */
    public function testModel()
    {
        $this->assertNotEmpty($this->object->model());
        $this->assertEquals($this, $this->object->model());
    }

    /**
     * @covers \Packfire\Core\ObjectObserver::on
     */
    public function testOn()
    {
        $this->object->on('change', array($this, 'changeListener'));
        $this->changed = false;
        $this->object->title = 'test';
        $this->assertTrue($this->changed);
    }

    private $changed;

    public function changeListener($sender, $args)
    {
        if ($args[0] == 'title' && $args[1] == 'test') {
            $this->assertEquals($this->object, $sender);
            $this->changed = true;
        }
    }

    /**
     * @covers \Packfire\Core\ObjectObserver::__set
     */
    public function testSet()
    {
        $msg = 'test title';
        $this->assertEmpty($this->title);
        $this->object->title = $msg;
        $this->assertEquals($msg, $this->title);
    }

    /**
     * @covers \Packfire\Core\ObjectObserver::__get
     */
    public function testGet()
    {
        $msg = 'test title';
        $this->assertEmpty($this->object->title);
        $this->title = $msg;
        $this->assertEquals($msg, $this->object->title);
    }

    /**
     * @covers \Packfire\Core\ObjectObserver::__isset
     */
    public function testIsset()
    {
        $msg = 'test title';
        $this->assertFalse(isset($this->object->title));
        $this->title = $msg;
        $this->assertTrue(isset($this->object->title));
    }

    /**
     * @covers \Packfire\Core\ObjectObserver::__unset
     */
    public function testUnset()
    {
        $msg = 'test title';
        $this->title = $msg;
        $this->assertTrue(isset($this->object->title));
        unset($this->object->title);
        $this->assertFalse(isset($this->object->title));
    }

    /**
     * @covers \Packfire\Core\ObjectObserver::__call
     */
    public function testCall()
    {
        $this->assertFalse($this->call);
        $this->object->call();
        $this->assertTrue($this->call);
    }
}
