<?php
namespace Packfire\Core;

use Packfire\Event\EventObserver;

/**
 * Test class for Observable.
 * Generated by PHPUnit on 2012-09-03 at 06:57:19.
 */
class ObservableTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Packfire\Core\Observable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Observable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Packfire\Core\Observable::attach
     * @covers \Packfire\Core\Observable::notify
     * @covers \Packfire\Core\Observable::detach
     */
    public function testObserve() {
        $test = $this;
        $observable = $this->object;
        $data = 10;
        $closure = function($sender, $arg) use($observable, $test, &$data){
            $test->assertEquals($observable, $sender);
            $test->assertEquals(5, $arg);
            $data = $arg;
        };
        $eventObserver = new EventObserver($closure);
        $this->object->attach($eventObserver);
        $this->object->notify(5);
        $this->assertEquals(5, $data);
        $this->object->detach($eventObserver);
        $data = 10;
        $this->object->notify(5);
        $this->assertEquals(10, $data);
    }

}
