<?php

pload('packfire.core.pObservable');
pload('packfire.event.pEventObserver');

/**
 * Test class for pObservable.
 * Generated by PHPUnit on 2012-09-03 at 06:57:19.
 */
class pObservableTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pObservable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pObservable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testObserve() {
        $test = $this;
        $observable = $this->object;
        $data = 10;
        $closure = function($sender, $arg) use($observable, $test, &$data){ 
            $test->assertEquals($observable, $sender);
            $test->assertEquals(5, $arg);
            $data = $arg;
        };
        $eventObserver = new pEventObserver($closure);
        $this->object->attach($eventObserver);
        $this->object->notify(5);
        $this->assertEquals(5, $data);
        $this->object->detach($eventObserver);
        $data = 10;
        $this->object->notify(5);
        $this->assertEquals(10, $data);
    }

}
