<?php

pload('packfire.text.pString');

/**
 * Test class for pString.
 * Generated by PHPUnit on 2012-04-25 at 07:54:14.
 */
class pStringTest extends PHPUnit_Framework_TestCase {
    
    /**
     *
     * @var array
     */
    protected $rawString = array(
        'testing same thing over and over again  ',
        " \t killjoys         ",
        'Somewhere OVER THE RAINBOW!'
    );

    /**
     * @var array
     */
    protected $objects;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->objects = array();
        foreach($this->rawString as $str){
            $this->objects[] = new pString($str);
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pString::value
     */
    public function testValue() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals($this->rawString[$idx], $obj->value());
        }
    }

    /**
     * @covers pString::trim
     */
    public function testTrim() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(trim($this->rawString[$idx]),
                    $obj->trim()->value());
        }
    }

    /**
     * @covers pString::trimLeft
     */
    public function testTrimLeft() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(ltrim($this->rawString[$idx]),
                    $obj->trimLeft()->value());
        }
    }

    /**
     * @covers pString::trimRight
     */
    public function testTrimRight() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(rtrim($this->rawString[$idx]),
                    $obj->trimRight()->value());
        }
    }

    /**
     * @covers pString::split
     */
    public function testSplit() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $a = $obj->split(' ')->toArray();
            $this->assertEquals(explode(' ', $this->rawString[$idx]), $a);
        }
    }

    /**
     * @covers pString::replace
     */
    public function testReplace() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $result = $obj->replace('over', 'time');
            $this->assertEquals(str_replace('over', 'time',
                    $this->rawString[$idx]), $result);
        }
    }

    /**
     * @covers pString::indexOf
     */
    public function testIndexOf() {
        $this->assertEquals(4, $this->objects[0]->indexOf('ing'));
        $this->assertEquals(8, $this->objects[0]->indexOf('same'));
        $this->assertEquals(19, $this->objects[0]->indexOf('over'));
        $this->assertEquals(-1, $this->objects[0]->indexOf('nil'));
    }

    /**
     * @covers pString::lastIndexOf
     */
    public function testLastIndexOf() {
        $this->assertEquals(15, $this->objects[0]->lastIndexOf('ing'));
        $this->assertEquals(36, $this->objects[0]->lastIndexOf('in'));
        $this->assertEquals(0, $this->objects[0]->lastIndexOf('test'));
        $this->assertEquals(-1, $this->objects[0]->lastIndexOf('nil'));
    }

    /**
     * @covers pString::occurances
     */
    public function testOccurances() {
        $this->assertCount(2, $this->objects[0]->occurances('over'));
        $this->assertCount(1, $this->objects[1]->occurances('joy'));
        $this->assertCount(0, $this->objects[1]->occurances('tan'));
    }

    /**
     * @covers pString::substring
     */
    public function testSubstring() {
        $this->assertEquals('test', $this->objects[0]->substring(0, 4));
        $this->assertEquals('same', $this->objects[0]->substring(8, 4));
    }

    /**
     * @covers pString::toUpper
     */
    public function testToUpper() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(strtoupper($this->rawString[$idx]),
                    $obj->toUpper()->value());
        }
    }

    /**
     * @covers pString::toLower
     */
    public function testToLower() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(strtolower($this->rawString[$idx]),
                    $obj->toLower()->value());
        }
    }

    /**
     * @covers pString::padLeft
     */
    public function testPadLeft() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(str_pad($this->rawString[$idx], 5, ' ', STR_PAD_LEFT),
                    $obj->padLeft(' ', 5)->value());
            $this->assertEquals(str_pad($this->rawString[$idx], 5, '-', STR_PAD_LEFT),
                    $obj->padLeft('-', 5)->value());
        }
    }

    /**
     * @covers pString::padRight
     */
    public function testPadRight() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(str_pad($this->rawString[$idx], 5, ' ', STR_PAD_RIGHT),
                    $obj->padRight(' ', 5)->value());
            $this->assertEquals(str_pad($this->rawString[$idx], 5, '-', STR_PAD_RIGHT),
                    $obj->padRight('-', 5)->value());
        }
    }

    /**
     * @covers pString::padBoth
     */
    public function testPadBoth() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(str_pad($this->rawString[$idx], 5, ' ', STR_PAD_BOTH),
                    $obj->padBoth(' ', 5)->value());
            $this->assertEquals(str_pad($this->rawString[$idx], 5, '-', STR_PAD_BOTH),
                    $obj->padBoth('-', 5)->value());
        }
    }

    /**
     * @covers pString::length
     */
    public function testLength() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(strlen($this->rawString[$idx]),
                    $obj->length());
            $this->assertEquals(strlen(trim($this->rawString[$idx])),
                    $obj->trim()->length());
        }
    }

    /**
     * @covers pString::count
     */
    public function testCount() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals(strlen($this->rawString[$idx]),
                    $obj->count());
            $this->assertEquals(strlen(trim($this->rawString[$idx])),
                    $obj->trim()->count());
        }
    }

    /**
     * @covers pString::__toString
     */
    public function test__toString() {
        foreach($this->objects as $idx => $obj){
            /* @var $obj pString */
            $this->assertEquals($this->rawString[$idx],
                    $obj->__toString());
            $this->assertEquals($this->rawString[$idx],
                    (string)$obj);
        }
    }

}