<?php

pload('packfire.text.pText');

/**
 * Test class for pText.
 * Generated by PHPUnit on 2012-04-25 at 14:12:51.
 */
class pTextTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pText::truncate
     */
    public function testTruncate() {
        $this->assertEquals('How are you...', pText::truncate('How are you today?', 15));
        $this->assertEquals('How are...', pText::truncate('How are you today?', 10));
        $this->assertEquals('How...', pText::truncate('How are you today?', 5));
        $this->assertEquals('How are you-', pText::truncate('How are you today?', 15, '-'));
        $this->assertEquals('How are-', pText::truncate('How are you today?', 10, '-'));
        $this->assertEquals('How-', pText::truncate('How are you today?', 5, '-'));
    }

    /**
     * @covers pText::highlight
     */
    public function testHighlight() {
        $this->assertEquals('To get <b>over the</b> fence comes <b>over the</b> fear.',
                pText::highlight('To get over the fence comes over the fear.', 'over the'));
        $this->assertEquals('To get <a href="over the">over the</a> fence comes <a href="over the">over the</a> fear.',
                pText::highlight('To get over the fence comes over the fear.', 'over the', '<a href="$1">$1</a>'));
    }

    /**
     * @covers pText::stripTags
     */
    public function testStripTags() {
        $text = 'To get <b>over the</b> <i>fence</i> comes <b>over the</b> fear.';
        $this->assertEquals('To get over the fence comes over the fear.',
                pText::stripTags($text));
        $this->assertEquals('To get over the <i>fence</i> comes over the fear.',
                pText::stripTags($text, '<i>'));
    }

    /**
     * @covers pText::listing
     */
    public function testListing() {
        $this->assertEquals('harry, hermione and ron', pText::listing(array('harry', 'hermione', 'ron')));
        $this->assertEquals('harry, hermione or ron', pText::listing(array('harry', 'hermione', 'ron'), 'or'));
        $this->assertEquals('harry; hermione or ron', pText::listing(array('harry', 'hermione', 'ron'), 'or', '; '));
    }

    /**
     * @covers pText::rotate13
     */
    public function testRotate13() {
        $this->assertEquals('Tbbq qnl, Fve!', pText::rotate13('Good day, Sir!'));
        $this->assertEquals('Enqvb 241 vanpgvir.', pText::rotate13('Radio 241 inactive.'));
    }

    /**
     * @covers pText::rotate47
     */
    public function testRotate47() {
        $this->assertEquals('v@@5 52J[ $:CP', pText::rotate47('Good day, Sir!'));
        $this->assertEquals('|2J52JP #25:@ ac` :?24E:G6]', pText::rotate47('Mayday! Radio 241 inactive.'));
    }

}