<?php

pload('packfire.application.cli.pCliServiceBucket');
pload('packfire.ioc.pServiceBucket');

/**
 * Test class for pCliServiceBucket.
 * Generated by PHPUnit on 2012-09-17 at 07:25:16.
 */
class pCliServiceBucketTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pCliServiceBucket
     */
    protected $object;
    
    /**
     *
     * @var pServiceBucket 
     */
    protected $bucket;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->bucket = new pServiceBucket();
        $this->object = new pCliServiceBucket($this->bucket);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pCliServiceBucket::load
     */
    public function testLoad() {
        $this->object->load();
        $this->assertTrue($this->bucket->contains('config.routing'));
        $this->assertInstanceOf('pCliRouter', $this->bucket->pick('router'));
    }

}