<?php

pload('packfire.application.cli.pCliAppRequest');

/**
 * Test class for pCliAppRequest.
 * Generated by PHPUnit on 2012-09-17 at 07:05:03.
 */
class pCliAppRequestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pCliAppRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new pCliAppRequest(array('-t', '--run', 'area', '-i=5'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pCliAppRequest::params
     */
    public function testParams() {
        $this->assertTrue($this->object->params()->get('t'));
        $this->assertEquals(5, $this->object->params()->get('i'));
        $this->assertEquals('area', $this->object->params()->get('run'));
    }

    /**
     * @covers pCliAppRequest::method
     */
    public function testMethod() {
        $this->assertEquals('cli', $this->object->method());
    }

}
