<?php
namespace Packfire\Application\Cli;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2012-09-17 at 07:05:03.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Request(array('-t', '--run', 'area', '-i=5'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Request::params
     */
    public function testParams() {
        $this->assertEquals('-t', $this->object->params()->get(0));
        $this->assertEquals('--run', $this->object->params()->get(1));
        $this->assertEquals('-i=5', $this->object->params()->get(3));
    }

    /**
     * @covers Request::method
     */
    public function testMethod() {
        $this->assertEquals('cli', $this->object->method());
    }

}
