<?php
namespace Packfire\Application\Cli;

/**
 * Test class for Response.
 * Generated by PHPUnit on 2012-09-17 at 07:23:29.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Response();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Response::output
     */
    public function testOutput() {
        $this->assertNull($this->object->output());
        $this->assertEquals(5, $this->object->output(5));
        $this->assertEquals(5, $this->object->output());
    }

}