<?php
namespace Packfire\Debugger\Output;

/**
 * Test class for Firebug.
 * Generated by PHPUnit on 2012-09-30 at 02:03:42.
 */
class FirebugtTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Packfire\Debugger\Output\Firebug
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @covers \Packfire\Debugger\Output\Firebug::__construct
     */
    protected function setUp()
    {
        $this->object = new Firebug();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Packfire\Debugger\Output\Firebug::output
     */
    public function testOutput()
    {
        ob_start();
        $this->object->output();
        $content = ob_get_clean();
        $this->assertEquals('', $content);
    }

    /**
     * @covers \Packfire\Debugger\Output\Firebug::write
     */
    public function testWrite()
    {
        $this->object->write('test');
        ob_start();
        $this->object->output();
        $content = ob_get_clean();
        $this->assertTrue(strpos($content, 'console.log("test");') > 0);
    }
}
