<?php

pload('packfire.view.pTheme');

/**
 * Test class for pTheme.
 * Generated by PHPUnit on 2012-09-19 at 02:49:42.
 */
class pThemeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var pTheme
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $this->getMockForAbstractClass('pTheme');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pTheme::fields
     */
    public function testFields() {
        $this->assertInstanceOf('pMap', $this->object->fields());
    }

}