<?php
namespace Packfire\View;

use Packfire\Collection\Map;
use Packfire\Route\Http\Route;
use Packfire\Route\Http\Router;
use Packfire\Template\Template;

require_once('test/Mocks/View.php');
require_once('test/Mocks/Config.php');
use Packfire\Test\Mocks\View;
use Packfire\Test\Mocks\Config;

/**
 * Test class for View.
 * Generated by PHPUnit on 2012-03-25 at 13:34:52.
 */
class ViewTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new View();

        $router = new Router();
        $configData = new Map(array('rewrite' => '/home', 'actual' => 'Rest'));
        $router->add('home', new Route('home', $configData));
        $services->put('router', $router);

        $mockConfig = new Config();
        $services->put('config.app', $mockConfig);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers View::create
     */
    public function testCreate() {
        $this->object->state(new Map(array('tag' => 'five  ')));
        $this->object->using(new Template('data: {tag} route: {route} {binder}'));
        $this->assertEquals('data: five route: http://example.com/test/home test2', $this->object->render());
    }

}

